# Web Scraping Assignment with Beautiful Soup, Selenium and Exception Handling concepts

In [1]:
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementClickInterceptedException,ElementNotInteractableException

Importing all the necessary dependencies here.

Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/

You need to find following details:

A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [57]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the wikipedia
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)



#scraping names of the video
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')
    
time.sleep(2)    
#scraping rank of the video
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    rank.append('No details available')
    
    time.sleep(2)
#scraping artist/uploader of the video
artist=[]
try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')
    
time.sleep(2)    
#scraping views of the video
views=[]
try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:#handling no such element exception
    views.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    views.append('No details available') 
time.sleep(2)    
#scraping views of the video
upload_date=[]
try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
except NoSuchElementException:#handling no such element exception
    upload_date.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    upload_date.append('No details available')

In [58]:
#preparing dataframe
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                "Uploader/artist":artist,
                "Date of upload":upload_date,
                "Views(in billion)":views})

In [59]:
df

,Rank,Name,Uploader/artist,Date of upload,Views(in billion)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.23
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.75
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.18
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.62
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.42
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.01
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,8.,"""Masha and the Bear – Recipe for Disaster""[22]",Get Movies,"January 31, 2012",4.48
8,9.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",4.48
9,10.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.47
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.35
11,12.,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.86
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.70
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.65
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.53
15,16.,"""Sorry""[34]",Justin Bieber,"October 22, 2015",3.51
16,17.,"""Counting Stars""[35]",OneRepublic,"May 31, 2013",3.51
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.41
18,19.,"""Girls Like You""[37]",Maroon 5,"May 31, 2018",3.24
19,20.,"""Axel F""[38]",Crazy Frog,"June 16, 2009",3.24
20,21.,"""Faded""[39]",Alan Walker,"December 3, 2015",3.23
21,22.,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.23
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.18
23,24.,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.17
24,25.,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.17
25,26.,"""Shake It Off""[44]",Taylor Swift,"August 18, 2014",3.15
26,27.,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.14
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.10
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.06
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.04

Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [70]:
driver=webdriver.Chrome("chromedriver.exe")

In [90]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 


time.sleep(2)
# Opening the bcci.tv
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(2)
#going to international fixtures page
fixtures=driver.find_element_by_xpath("/html/body/nav/div/div[2]/ul[1]/li[2]/a")
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    

time.sleep(2)
# scrape match details urls from xpath    
urls=[]
match_page=driver.find_elements_by_xpath("//div[@class='fixture-card-main col-lg-3 col-md-6 col-sm-12 ng-scope']/a")  
for i in match_page:
    urls.append(i.get_attribute('href'))
time.sleep(1)   
# make empty lists
match=[] 
series=[]
place=[]
date=[]
Time=[]
all_text = []
venue = []


for i in urls:                 #list of urls of match description pages
    driver.get(i)
    
    time.sleep(2)
    #scarping match title
    try:                    
        match_title=driver.find_element_by_xpath("//p[@class='ng-binding']/span")
        match.append(match_title.text)
    except NoSuchElementException:#handling no such element exception
        match.append('No details available')
    
    time.sleep(2)
    #scarping series title    
    try:
        series_title=driver.find_element_by_xpath("//h1[@class='ng-binding']/strong")
        series.append(series_title.text)
    except NoSuchElementException:#handling no such element exception
        series.append("No details Available")
    
    time.sleep(2)
    #scarping date of match 
    try:
        date_title=driver.find_element_by_xpath("//h5[@class='ng-binding']/strong")
        date.append(date_title.text)
    except NoSuchElementException:#handling no such element exception
        date.append("No details Available")      
    
    time.sleep(2)
    #scarping time of the match    
    try:
        time_title=driver.find_element_by_xpath("//div[@class='match-card-right match-schedule']/span")
        Time.append(time_title.text)
    except NoSuchElementException:#handling no such element exception
        Time.append("No details Available")    
      
    time.sleep(2)
     #scarping match venue    
    try:
        place_title=driver.find_element_by_xpath("//div[@class='ng-binding ng-scope']")
        venue.append(place_title.text)
    except NoSuchElementException:#handling no such element exception
        place.append("No details Available")
        
     # split place from text
for i in venue:
    all_text.append(i.split())
for i in all_text:
    place.append(i[-1::]) 
    
time.sleep(2)       
#preparing the dataframe
df=pd.DataFrame({"Match":match,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":Time})
df

Empty DataFrame
Columns: [Match, Series, Place, Date, Time]
Index: []

Q3 - Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/ You need to find following details: A) Name B) Description Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [96]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the guru99.com
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)

In [97]:
#clicking on selenium option under testing menu open its tutorial
selenium_link=driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a")
try:
    selenium_link.click()
except ElementNotInteractableException:          #handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))
time.sleep(2)

In [99]:
#clicking on Selenium Exception Handling (Common Exceptions List) under Advance Webdriver Stuff!
exception_handle_link=driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[2]")
try:
    exception_handle_link.click()
except ElementNotInteractableException:      #handling element not clickable exception
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(2)

In [100]:
#scraping exceptions names
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:               #handling no such element exception
    name.append('No details available')
time.sleep(2)

In [101]:
#scraping exceptions description
desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list[1:]:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')
time.sleep(2)

In [102]:
#creating dataframe
df=pd.DataFrame({"Exception_name":name,
                "Description":desc})
df

,Exception_name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

Q4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/ You have to find following details: A) Rank B) State C) GSDP(18-19) D) GSDP(17-18) E) Share(2017) F) GDP($ billion) Note: - From statisticstimes home page you have to reach to economy page through code.

In [2]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

In [3]:
economy = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()
time.sleep(2)

In [4]:
india = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()
time.sleep(2)

In [6]:
ind_eco = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
ind_eco.click()
time.sleep(2)

# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

In [7]:
try: # Scraping Rank
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
try: # Scraping GDP billion
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

,Rank,State,GSDP (Cr INR at Current prices) (19-20),GSDP (Cr INR at Current prices) (18-19),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

Q.5 scrape the details of trending repositories on Github.com. Url = https://github.com/

You have to find the following details:

A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [32]:
url = "https://github.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

In [33]:
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore.click()
time.sleep(2)

In [34]:
trending = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
trending.click()
time.sleep(2)

In [37]:
# Empty list
Repository = []
Repository_des = []
Contributors = []
Language = []

In [38]:
try: # Scraping repository
    for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
        Repository.append(i.text)
except NoSuchElementException as e:
    print("-")

In [49]:
try: # Scraping Repository description
    for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
        Repository_des.append(i.text)
except NoSuchElementException as e:
    print("-")

In [40]:
try: # Scraping Contributors count
    for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):
        Contributors.append(i.text)
except NoSuchElementException as e:
    print("-")

In [55]:
try: # Scraping language
    for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):
        Language.append(i.text)
except NoSuchElementException as e:
    print("-")

In [56]:
print(len(Language))

38

In [57]:
# Creating data frame 
github = pd.DataFrame({"Repository title":Repository[:22],"Repository description":Repository_des[:22],
                       "Contributors count": Contributors[:22],"Language used": Language[:22]})
github

,Repository title,Repository description,Contributors count,Language used
0,almerico / bombardier,bombardier,56,HCL
1,iaddis / metalnes,Transistor level NES simulation,16,JavaScript
2,AppFlowy-IO / AppFlowy,AppFlowy is an open-source alternative to Noti...,906,Rust
3,cat-milk / Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,495,JavaScript
4,HashLips / hashlips_art_engine,HashLips Art Engine is a tool used to create m...,"2,407",Python
5,freqtrade / freqtrade,"Free, open source crypto trading bot","3,462",Go
6,erkexzcx / stoppropaganda,DOS application to stop pro-Russian aggression...,28,Python
7,AlexTrushkovsky / NoWarDDoS,DDoS Russian websites to help Ukraine to win t...,55,Python
8,MHProDev / MHDDoS,"Best DDoS Attack Script Python3, Cyber Attack ...",425,HTML
9,ajax-lives / NoRussian,Volunteer DoS tool via HTML + JS,38,Python
10,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,"4,814",HTML
11,palahsu / DDoS-Ripper,DDos Ripper a Distributable Denied-of-Service ...,130,Python
12,curated-intel / Ukraine-Cyber-Operations,Curated Intelligence is working with analysts ...,19,Python
13,techchipnet / CamPhish,Grab cam shots from target's phone front camer...,348,Python
14,ytdl-org / youtube-dl,Command-line program to download videos from Y...,"7,211",Python
15,github / advisory-database,Security vulnerability database inclusive of C...,35,Python
16,cyprosecurity / API-SecurityEmpire,API Security Projecto aims to present unique a...,51,Shell
17,LimerBoy / Impulse,💣 Impulse Denial-of-service ToolKit,338,Python
18,RunaCapital / awesome-oss-alternatives,Awesome list of open-source startup alternativ...,324,C#
19,jseidl / GoldenEye,GoldenEye Layer 7 (KeepAlive+NoCache) DoS Test...,396,HCL
20,Luzhnuy / attacker,"Scripts to build your own IPsec VPN server, wi...",27,JavaScript
21,hwdsl2 / setup-ipsec-vpn,"A curated list of awesome Python frameworks, l...","4,864",Rust

Q.6 Scrape the details of top 100 songs on billboard.com. Url = https://www.billboard.com/

You have to find the following details:

A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [124]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)


#clicking the hot 100 songs link
charts=driver.find_element_by_xpath("/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)


#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)   

#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(2)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)
#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)

In [125]:
#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

Empty DataFrame
Columns: [Song_Name, Artist_Name, Last_week_rank, Peak, Weeks_on_chart]
Index: []

Q7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/ You have to find the following details: A) Name B) Designation C) Company D) Skills they hire for E) Location Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [126]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

In [128]:
#clicking on recruiters link
recruiters=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

In [129]:
#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)


#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)

In [130]:
#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2)

In [131]:
#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
16,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
19,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
31,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
33,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
34,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
35,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
40,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
43,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
45,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
46,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
47,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."
48,Radha Manivasagam,HR Executive,Techcovery,Bengaluru / Bangalore,"Python, Artificial Intelligence, Machine Learn..."
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."

Q8. Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ You have to find the following details: A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

In [112]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Book_name = []
Author_name = []
Volume_sold = []
Publisher = []
Genre = []

Legality Response number from our URL is: <Response [200]>

In [113]:
try: # Scraping Book name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        Book_name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Author name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        Author_name.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Volume sold
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Publisher
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        Publisher.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        Genre.append(i.text)
except NoSuchElementException as e:
    print("-")

In [114]:
# Creating data frame 
Books=pd.DataFrame({'Book Name': Book_name, 'Author Name': Author_name, 'Volume Sold': Volume_sold,
                    'Publisher': Publisher, 'Genre' : Genre})
Books

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q.9 Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [115]:
url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

name = []
year = []
genre = []
runtime = []
rating = []
vote = []

Legality Response number from our URL is: <Response [200]>

In [116]:
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Year span
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Run time
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
try: # Scraping votes
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")

In [117]:
# Creating a dataframe 
imdb=pd.DataFrame({'Name':name, 'Year Span':year, 'Genre':genre, 'Run Time':runtime, 'Ratings':rating, 'Votes':vote})
imdb

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,957,638"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"967,213"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"932,500"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"279,171"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"239,352"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,834"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,556"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"185,934"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,365"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"222,230"

Q.10 Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code.

In [118]:
url = "https://archive.ics.uci.edu/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

respository=driver.find_element_by_xpath("//span[@class='normal']/b/a")
respository.click()
    
Name=[]
Type=[]
Task=[]
Attribute=[]
No_of_Instance=[]
No_of_Attribute=[]
Year=[]

Legality Response number from our URL is: <Response [200]>

In [119]:
# Scrapping data for dataset name
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
# Scrapping data for data type
try:
    types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')
    
# Scrapping data for default task
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
        
# Scrapping data for attribute type
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
    Attribute.append('-')
# Scrapping data for number of instances
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
        
# Scrapping data for number of attributes
try:
    attribute_no=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
        
# Scrapping data for the year details
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')

In [120]:
# Creating the dataframe
df=pd.DataFrame({"Dataset Name":Name, "Data Type":Type, "Default Task":Task, "Attribute Type":Attribute, 
                 "No of instances":No_of_Instance, "No of atrributes":No_of_Attribute, "Year":Year})
df

,Dataset Name,Data Type,Default Task,Attribute Type,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021